name: Auto Assign Reviewers
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    types: [opened]
jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Assign reviewers based on author
        uses: actions/github-script@v6
        with:
          script: |
            const author = context.payload.pull_request.user.login;
            const prNumber = context.payload.pull_request.number;

            // Skip if PR is from a fork
            if (context.payload.pull_request.head.repo.full_name !== context.payload.repository.full_name) {
              core.info('PR is from a fork, skipping reviewer assignment.');
              return;
            }

            let reviewers = [];
            const reviewerMap = {
              'MichielStock': ['cvigilv'],
              'cvigilv': ['MichielStock'],
              'default': ['MichielStock', 'cvigilv']
            };

            reviewers = reviewerMap[author] || reviewerMap['default'];
            reviewers = reviewers.filter(reviewer => reviewer !== author);

            if (reviewers.length > 0) {
              await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
                reviewers: reviewers
              });
            }
