name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['lts', '1']
        os: [ubuntu-latest, windows-latest, macOS-latest]
        julia-arch: [x64]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Julia
      uses: julia-actions/setup-julia@v2
      with:
        version: ${{ matrix.julia-version }}
        arch: ${{ matrix.julia-arch }}

    - name: Cache Julia packages
      uses: julia-actions/cache@v2

    - name: Install dependencies
      uses: julia-actions/julia-buildpkg@v1

    - name: Run tests
      uses: julia-actions/julia-runtest@v1

    - name: Process coverage
      uses: julia-actions/julia-processcoverage@v1

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: lcov.info
